spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    schemas: ${DATABASE_SCHEMA}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth_api

  h2:
    console:
      enabled: false

  flyway:
    baseline-description: << Schema PROD Flyway >>
    schemas: auth_api
    locations: classpath:db/migration/postgres
