server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    data: "classpath:data.sql"
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password:

  jpa:
  show-sql: true
  hibernate:
    ddl-auto: create

  h2:
    console:
      enabled: true

  jackson:
    time-zone: UTC

  jpa:
    hibernate:
      ddl-auto: create

# Logging
logging:
  level:
    org:
    springframework: INFO

# JWT
jwt:
  secret: "auth-api"

documentation:
  swagger:
    enabled: true
